### ISSUE TITLE
ESM Directory Import error with Remix 2 base template

### ISSUE THREAD

**Issue by joietej** [remix-pwa/monorepo#112]
Hi, 
I am getting following error while running remix 2 app using "npm run dev".

Error: Directory import '/Projects/remix/my-remix-app-v2/node_modules/@remix-pwa/cache/node_modules/buffer/' is not supported resolving ES modules imported from /Projects/remix/my-remix-app-v2/node_modules/@remix-pwa/cache/dist/src/cache.js
Did you mean to import buffer/index.js?

**Comment by ShafSpecs** [comment]
> Hi, I am getting following error while running remix 2 app using "npm run dev".
> 
> Error: Directory import '/Projects/remix/my-remix-app-v2/node_modules/@remix-pwa/cache/node_modules/buffer/' is not supported resolving ES modules imported from /Projects/remix/my-remix-app-v2/node_modules/@remix-pwa/cache/dist/src/cache.js Did you mean to import buffer/index.js?

Add `@remix-pwa/cache`, `@remix-pwa/strategy` and `@remix-pwa/sw` to your `remix.config.js` - `serverDependenciesToBundle` field. A shorthand is:
```js
export default {
 /* ... */
 serverDependenciesToBundle: [
    /@remix-pwa\/.*/,
  ],
}
```

I should add this to the docs 'Gotcha' section

**Comment by joietej** [comment]
Thanks !

**Comment by itsMapleLeaf** [comment]
> > Hi, I am getting following error while running remix 2 app using "npm run dev".
> > Error: Directory import '/Projects/remix/my-remix-app-v2/node_modules/@remix-pwa/cache/node_modules/buffer/' is not supported resolving ES modules imported from /Projects/remix/my-remix-app-v2/node_modules/@remix-pwa/cache/dist/src/cache.js Did you mean to import buffer/index.js?
> 
> Add `@remix-pwa/cache`, `@remix-pwa/strategy` and `@remix-pwa/sw` to your `remix.config.js` - `serverDependenciesToBundle` field. A shorthand is:
> 
> ```js
> export default {
>  /* ... */
>  serverDependenciesToBundle: [
>     /@remix-pwa\/.*/,
>   ],
> }
> ```
> 
> I should add this to the docs 'Gotcha' section

Sorry in advance if my wording is too harsh, but this isn't a proper solution. Not only is bundling suboptimal in some cases, in others it's not possible. The ideal solution is for remix-pwa to correctly distribute itself as an ES module that can be consumed directly from Node.js. [tshy](https://www.npmjs.com/package/tshy), [tsup](https://tsup.egoist.sh/), and other tools can make this easier.

I'm happy to contribute a PR for this or assist in any other way 🙂

**Comment by ShafSpecs** [comment]
> Sorry in advance if my wording is too harsh, but this is a workaround, not a proper solution. Not only is bundling suboptimal in some cases, in others it's not possible.

Didn't think of it like that. Thanks for the heads up 👍 

> I'm happy to contribute a PR for this or assist in any other way 🙂

Sure thing ❤️! I won't be back to active development till next week but in the meantime, PRs are welcome. P.S. Please don't open a PR to main directly, rather build upon the `dev` branch and then PR to it. Merging to main directly releases your changes as `latest` without pre-checks
