### ISSUE TITLE
Wrong conditionals used in compiler

### ISSUE THREAD

**Issue by ShafSpecs** [remix-pwa/monorepo#116]
https://github.com/remix-pwa/monorepo/blob/fadff4f66e0246fad012f69c4437af11346bb22d/packages/dev/compiler/compiler.ts#L78

should be a `!==` and not `===`

**Comment by Sarabadu** [comment]
What is the reason to override the node enc to be always prods

**Comment by ShafSpecs** [comment]
> What is the reason to override the node enc to be always prods

Cause when running `remix-pwa build`, remix-pwa tends to use env from the local environment (development, by default). This means stuffs not meant to make its way into production ends up getting into production. Notably, `logger`. Which is supposed to be `null` in production
