### ISSUE TITLE
Usage with Vite

### ISSUE THREAD

**Issue by Knaackee** [remix-pwa/monorepo#123]
At first, thanks for the great work!

I am getting the following error while using remix-pwa with the new remix vite plugin.
But I think the issue is not vite related since `remix-pwa dev` isnt using it. 

Is it an ESM problem?

```
> remix-pwa dev

🏗️ Building Service Worker in development mode...

💿 Built Service Worker in: 21.477ms
👀 Watching for changes in the service worker file...
X [ERROR] glob is not a function [plugin sw-assets-module]

    ../../../node_modules/esbuild/lib/main.js:1434:27:
      1434 │         let result = await callback({
           ╵                            ^
```

**Comment by ShafSpecs** [comment]
👋 @Knaackee! Vite in Remix PWA isn't officially supported yet due to the new nature of Remix, I am currently working on it (within this branch: https://github.com/remix-pwa/monorepo/tree/feat/vite) and hope to push out an *unstable* but usable plugin before 2023 closes. 

Related issue: https://github.com/remix-pwa/remix-pwa/issues/136

**Comment by Knaackee** [comment]
Hey @ShafSpecs! 

This is great!

Is there anything I could help with?

**Comment by ShafSpecs** [comment]
> Hey @ShafSpecs! 
> 
> This is great!
> 
> Is there anything I could help with? 

Thanks for the gesture, but atm, no. If you are on Discord tho, you can join the Remix Discord server, within the "showcase" forum, you can find Remix PWA forum there were I discuss updates and more frequently. Plus resources are exchanged by community members

**Comment by ShafSpecs** [comment]
https://github.com/remix-pwa/monorepo/pull/124

Remix  PWA + Vite PR

**Comment by ShafSpecs** [comment]
Remix PWA v4 has been released: https://remix-pwa.run
