### ISSUE TITLE
sw: Asset cache in precache handler not initialised correctly

### ISSUE THREAD

**Issue by rrelmy** [remix-pwa/monorepo#131]
In [packages/sw/src/message/precacheHandler.ts](https://github.com/remix-pwa/monorepo/blame/d5aa5b4f99e3d6a4b1cab513a86339de3185de21/packages/sw/src/message/precacheHandler.ts#L95)

The `assetCache` is not initialized, resulting in a cache named `rp-undefined` being created.

Unlike `dataCache` and `documentCache` the corresponding asset variable is not initialized with `this.assetCacheName`.
Then `this.assetCacheName` is checked if it's a string, but the always undefined `assetCache` variable is used to open the cache.

For some reason there is a `@ts-expect-error` which hides this error.

**Comment by ShafSpecs** [comment]
> In [packages/sw/src/message/precacheHandler.ts](https://github.com/remix-pwa/monorepo/blame/d5aa5b4f99e3d6a4b1cab513a86339de3185de21/packages/sw/src/message/precacheHandler.ts#L95)
> 
> The `assetCache` is not initialized, resulting in a cache named `rp-undefined` being created.
> 
> Unlike `dataCache` and `documentCache` the corresponding asset variable is not initialized with `this.assetCacheName`. Then `this.assetCacheName` is checked if it's a string, but the always undefined `assetCache` variable is used to open the cache.
> 
> For some reason there is a `@ts-expect-error` which hides this error.

Thanks for spotting this! I am currently re-writing `sw` on the `feat/vite` branch. And caching is one of the main reasons for doing so, including deprecation of `cache` package :+1:

**Comment by ShafSpecs** [comment]
Update: Issues hasn't been forgotten. Just drowning in work atm, hope to be back in a few weeks 👍

**Comment by ShafSpecs** [comment]
*Removed support for `esbuild`., so this issue won't be fixed*

Precaching support in Vite is present, but no utility yet from `remix-pwa`. Would be providing solutions soon
