### ISSUE TITLE
Getting started not working properly

### ISSUE THREAD

**Issue by Canic** [remix-pwa/monorepo#151]
Hey there,

I'm attempting to upgrade to remix/pwa@4.0. However, after running:

`
npx remix-pwa sw
`

I encounter the following error:

`
Generating TypeScript service worker file...
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '/home/canic/remix-echarge/templates/entry.worker.ts'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/canic/remix-echarge/templates/entry.worker.ts'
}

Node.js v20.10.0
`

Additionally, I noticed that the entry.worker.js file hasn't been updated and still refers to old dependencies, as per the upgrade documentation:
https://github.com/remix-pwa/monorepo/blob/main/templates/app/entry.worker.ts

Am I missing something here?

**Comment by ShafSpecs** [comment]
Just tested this version out and it works on my PC, no problem. I am using Windows (11) and I'm running it in the root of a Remix project (the docs folder)

![image](https://github.com/remix-pwa/monorepo/assets/69679506/e6556c1b-49b1-4727-ac29-432eadf0a5f1)

**Comment by ShafSpecs** [comment]
Thanks for the PR. Moving that as well as other new stuffs to `latest`: https://github.com/remix-pwa/monorepo/pull/154

Docs should be updated in a few minutes
