### ISSUE TITLE
Incorrect sourmap on build due to plugin vite-plugin-remix-pwa:loader

### ISSUE THREAD

**Issue by hieuhlc** [remix-pwa/monorepo#167]
I got this error when I was running `remix vite:build`

```[plugin vite-plugin-remix-pwa:loader] Sourcemap is likely to be incorrect: a plugin (vite-plugin-remix-pwa:loader) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help```

My vite.config.ts file:

```javascript
export default defineConfig({
  server: { port: 3000 },
  build: { sourcemap: true },
  plugins: [
    remix({
      ignoredRouteFiles: ["**/.*", "**/*.css", "**/*.test.{js,jsx,ts,tsx}"],
      routes: async (defineRoutes) => flatRoutes("routes", defineRoutes),
      // serverModuleFormat: "cjs",
      // browserNodeBuiltinsPolyfill: {
      //   modules: { buffer: true, events: true, process: true },
      // },
    }),
    remixPWA(),
    cjsInterop({
      dependencies: ["lodash", "usehooks-ts", "rc-table", "@sentry/remix"],
    }),
    tsconfigPaths({ root: __dirname }),
  ],
});
```

I'm using remix v2.8.1 and @remix-pwa v3.0.0

**Comment by ShafSpecs** [comment]
Are you requesting sourcemaps somewhere within your apps? The error is thrown because remix-pwa employs a plugin to change the source code present in your root file (inject service worker registration) but it should not warrant an error about sourcemaps

**Comment by ShafSpecs** [comment]
Or are you generating sourcemaps elsewhere? Perhaps a mismatch has occurred during the bundling process.

**Comment by hieuhlc** [comment]
Hi @ShafSpecs here is a repo you can try. I created it using `npx create-remix@latest` and install remix-pwa latest.

https://github.com/hieuhlc/remix-pwa-demo

**Comment by ShafSpecs** [comment]
Very weird
![image](https://github.com/remix-pwa/monorepo/assets/69679506/09883efe-4537-4da9-8c52-40ad3ee9856b)
I am not getting any errors at all @hieuhlc, could you clear your npm cache + node modules + lock file and try again?

**Comment by hieuhlc** [comment]
@ShafSpecs no you need to run build not run dev

**Comment by hieuhlc** [comment]
yes @ShafSpecs how can we fix this? It says the sourcemap for the transformation was not generated

**Comment by ShafSpecs** [comment]
> yes @ShafSpecs how can we fix this? It says the sourcemap for the transformation was not generated

Not sure. Would check it out as well as solutions, but seems to be a side effect of generating source maps in production. Doesn't break things. Mostly.
