### ISSUE TITLE
Implementing push notifications

### ISSUE THREAD

**Issue by rhiannonbgrant** [remix-pwa/monorepo#171]
Hi there, I have installed V4 and it works well so far, main reason for using the plugin is that I want to implement push notifications, I know the use to be a package @remix-pwa/push, but I think it is depreciated, is there a way to do this now or are you working on something that will do this? I can't find anything on the current website. If this is the wrong place for this message please point me somewhere I can ask.

**Comment by ShafSpecs** [comment]
https://github.com/remix-pwa/monorepo/tree/feat/push
This branch is where I intend to work on push - the old push package is available, though under the name `@remix-pwa/old-push`. I intend to get push out quickly 👍

**Comment by rhiannonbgrant** [comment]
Thanks @ShafSpecs, can't wait to try the new package out when it lands, I'll be keeping an eye out. :)

**Comment by ShafSpecs** [comment]
Guide to Push API can be found here: https://remix-pwa.run/docs/main/push-api

**Comment by rhiannonbgrant** [comment]
Thanks so much @ShafSpecs , very excited to implement it.
