### ISSUE TITLE
"@remix-pwa/push": "^1.0.2" is missing

### ISSUE THREAD

**Issue by iChwn** [remix-pwa/monorepo#208]
![image](https://github.com/remix-pwa/monorepo/assets/29217999/0dd47c20-f8cd-4679-a2b5-b8d96998a53c)

I can't build mu project because I'm using 1.0.2 of remix-pwa/push

**Comment by ShafSpecs** [comment]
> 1.0.2

👋, sorry for the late response. The new `push` package version is `2.10.0` not `1.0.2`, if you want the old, legacy push package - that's available via `@remix-pwa/old-push`

**Comment by ShafSpecs** [comment]
*Closing this issue as stale*
