### ISSUE TITLE
how to setup Offline Page using remix-pwa

### ISSUE THREAD

**Issue by dhavalveera** [remix-pwa/monorepo#214]
Hello,

I am looking for a solution to setup Offline Page in PWA in my Remix App and I was looking around on Google and I came across your `remix-pwa` package, but in the documentation I wasn't able to find how to setup Offline Page in Remix App using `remix-pwa`.

can you please help me how to setup a offline page in Remix App using `remix-pwa`?

**Comment by ShafSpecs** [comment]
Hello @dhavalveera, setting up an offline oage using Remix PWA involves setting up a service worker, and handing it via a fetch handler. You can check out MDN for resources on how that looks like. Or if you don't mind waiting a bit, I am setting up an extensive guide on setting up a PWA from scratch :)

**Comment by dhavalveera** [comment]
> Hello @dhavalveera, setting up an offline oage using Remix PWA involves setting up a service worker, and handing it via a fetch handler. You can check out MDN for resources on how that looks like. Or if you don't mind waiting a bit, I am setting up an extensive guide on setting up a PWA from scratch :)

I would like to wait, can you give an ETA for this? @ShafSpecs

**Comment by ShafSpecs** [comment]
Not sure. It is **long**, currently a 30 mins read and still counting. I hope to make it an A-Z guide, but hopefully within the next few weeks (2)

**Comment by ShafSpecs** [comment]
https://shafspecs.hashnode.dev/remix-pwa-practical-guide :+1:
