### ISSUE TITLE
Question: remix-pwa inside electron

### ISSUE THREAD

**Issue by rares-lupascu** [remix-pwa/monorepo#251]
Hey

Did anyone try to use remix-pwa inside an electron app? Any feedback related to possible issues?

Thanks

**Comment by ShafSpecs** [comment]
Hello, I am not sure if it's possible to use Remix PWA within electron. What are you trying to achieve? I would recommend electron-vite with vite-pwa if you want to go down the electron + service worker/pwa route

**Comment by ShafSpecs** [comment]
*This issue won't be worked on, as it is out of scope for this project*
