### ISSUE TITLE
Module '"@remix-pwa/dev"' has no exported member 'WorkerDataFunctionArgs'.

### ISSUE THREAD

**Issue by dvnrsn** [remix-pwa/monorepo#262]
This happens in getting started https://remix-pwa.run/docs/main/default-fetch-handler#using-the-default-fetch-handler

**Comment by dvnrsn** [comment]
Weird because I see it here https://github.com/remix-pwa/monorepo/blob/dda9d68b1c69642679d6ff17658f21fe24c668d6/packages/dev/worker-build.ts#L18

**Comment by ShafSpecs** [comment]
Could you attempt re-installing? This seems like a TS error

**Comment by dvnrsn** [comment]
Yeah this happens with a fresh project

![CleanShot 2024-09-18 at 19 45 37@2x](https://github.com/user-attachments/assets/424002d7-a175-4c64-bb0e-fb17b133cf31)

**Comment by ShafSpecs** [comment]
Super weird. Looks like a TS server error to me, but definitely not a Remix PWA bug

I've encountered this kind of error a few times, sometimes relating to the entire file not being found in `tsconfig.json` 🤷

**Comment by ShafSpecs** [comment]
Could you attempt to import from the `sw` package?

**Comment by dvnrsn** [comment]
Ah ok I see it's in the sw package https://github.com/remix-pwa/monorepo/blob/dda9d68b1c69642679d6ff17658f21fe24c668d6/packages/sw/src/types.ts#L21

I ran `pnpm install -D @remix-pwa/sw` and restarted TS server. This seemed to work

**Comment by dvnrsn** [comment]
Should this installation step be added to this page
https://remix-pwa.run/docs/main/default-fetch-handler
and of course update the import?

**Comment by ShafSpecs** [comment]
Yes, I should. I'm heavily working on the docs nowadays.
