### ISSUE TITLE
ESM issue on Firefox

### ISSUE THREAD

**Issue by khanhicetea** [remix-pwa/monorepo#283]
Thanks for the lib,

I check the source then see register service worker type is `classic` ( So we can't use ESM modules ? )
I changed the register service worker type to `module` it work in Chromium browsers but not Firefox (because FF doesn't support ESM in SW)

Thanks

**Comment by ShafSpecs** [comment]
That's because Firefox doesnt support it yet, see: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker#browser_compatibility

**Comment by ShafSpecs** [comment]
You can't use import statements in the service worker currently, if you look at your built service worker, you will see that the whole thing is built into one file. Without any imports or `require()` statements

**Comment by khanhicetea** [comment]
Thanks for clarifying.
