### ISSUE TITLE
cacheFirst crash on Safari 17

### ISSUE THREAD

**Issue by rphlmr** [remix-pwa/monorepo#66]
Given this cache handler
```ts
cacheFirst({
	cache: assetCache,
	cacheQueryOptions: {
		ignoreSearch: true,
		ignoreVary: true,
	},
})
```
In a `defaultFetchHandler`
```ts
export const defaultFetchHandler: DefaultFetchHandler = ({
	context,
	request,
}) => {
	const type = matchRequest(request);

	if (type === "asset") {
		return assetsHandler(context.event.request);
	}

	if (type === "loader") {
		return dataHandler(context.event.request);
	}

	return context.fetchFromServer();
};
```

This crash on Safari 17 (beta and developper preview) on macOS.

Packages: @remix-pwa/strategy, @remix-pwa/cache

Throw on this line: https://github.com/remix-pwa/monorepo/blob/a65e6a1bdec58a5d12f6a89076724c9e9617f35b/packages/cache/src/cache.ts#L301

I'm trying to find why.

![CleanShot 2023-09-21 at 16 10 01](https://github.com/remix-pwa/monorepo/assets/20722140/ab78728e-e7c7-4f70-8cee-7d043dbedf78)

```console
Failed to load resource: FetchEvent.respondWith received an error: SyntaxError: The string did not match the expected pattern.
FetchEvent.respondWith received an error: SyntaxError: The string did not match the expected pattern.
```

**Comment by rphlmr** [comment]
At this point, a request can have many values in its `Content-Type`  header.
![image](https://github.com/remix-pwa/monorepo/assets/20722140/6f046890-408e-4a40-aa09-17fd5e160b1d)

**Comment by ShafSpecs** [comment]
Seems like this is fixed

**Comment by rphlmr** [comment]
Confirmed, all good!
