### ISSUE TITLE
Consider Remix v2 during `remix-pwa init` run

### ISSUE THREAD

**Issue by ShafSpecs** [remix-pwa/monorepo#72]
Weird bugs from not finding config file: what's going on?

https://github.com/remix-pwa/remix-pwa/issues/121

**Comment by ShafSpecs** [comment]
Btw, reduce the `try {...} catch (e) {...}` scope in the creation suite

**Comment by wonu** [comment]
I have the same issue on Windows, and figured out `url.pathToFileURL()` is needed to resolve an absolute path on Windows.
I was about to create PR to fix this, can I?

**Comment by ShafSpecs** [comment]
> I have the same issue on Windows, and figured out `url.pathToFileURL()` is needed to resolve an absolute path on Windows.

`process.cwd()` should return the correct path for both Unix and Non-Unix systems. Can you please try clearing your npm cache then re-trying? In the issue mentioned above, he was able to get it working in a codespace

**Comment by wonu** [comment]
Sorry for being vague, I meant module resolution when importing:
https://github.com/remix-pwa/monorepo/blob/e498b6a57c6356786e98168164538a7a4b0dc01d/packages/dev/cli/create.ts#L109

I think it should be
```ts
import { fileURLToPath, pathToFileURL } from 'url';
const remixConfig = await import(pathToFileURL(resolve(projectDir, 'remix.config.js')).href).then(m => m.default);
```

**Comment by ShafSpecs** [comment]
Thanks for the tip, would release a nightly build ASAP

**Comment by ShafSpecs** [comment]
Would create a PR for this soon.
